# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d81aa0ca1a5587486b8876826f0afc568ae82f5f2b397d35744eba6b8266b9173878b6c2c3b52a30164cbbecf2fd1354a4c53d62e692e331beb70a8af6e4bf9

test:
  secret_key_base: f66fbac77f298bbce70d11606a2eefe015c6e6833c407a7f7d7d229784b9d98405fcd55ea5a74c5772860efb682a04a49aa987a172079695c4e842807eac92d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
